import React from 'react';
import ReactDOM from 'react-dom';
import App from './components/App/App'
/*
ESTADO:

{
    users,
    trips
}

users: {
    order: [1, 32, 3232, 3212, 3234],
    byid: {
        id, //autogenerated
        email,
        name,
        description
        howManyTrips //auto start in 0
    }
}

trips: {
    id, // autogenerated
    fromWhere,
    toWhere,
    whoJoined: [1213, 421 ,321], // auto in 1 (createById)
    createdById,
    description,
    date,
    time 
}
*/


ReactDOM.render(
    <App />, 
    document.getElementById('root')
);

